services:
  backend-vsantos:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-vsantos
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
